[discovery]
host = "gc-kg-db-do-user-7802184-0.b.db.ondigitalocean.com"
user = "user_gc_prod"
password = "must!123@"
port = 25060
database = "gc_prod"

[capture]
spreadsheet = "1K0DkZiAMMWOPgA2SAc4AMw_fJhtQqj2iZ4ZnJfoCV_k"

[sap]
spreadsheet = "1RKONCl4rEU7VfPhr8Moz2tLH5gw2hW1HFPZ6VYVuw70"

[json_sap]
type = "service_account"
project_id = "kognisi-dashboard"
private_key_id = "0a318e986d8fe955a4deb5553fefcadca7eb38a1"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC6RvFm6akEewj2\nsGngL7epkzl7/zOHckokbwOEDkZHK+veD7aFRHanad78djVWIc0t+dz43m0/1wmm\ncOC62ObM5hQzPI5QykPA4RYNrp48fb+w2K/kfXWB955Yf7H5nuv1flXcBG6XH2QS\nBwELqYQ5POwIo0SXbMw6NWkshDCsGlvKmqUrIWOTde7BQovwVYN0ZKYwaO5Ow3Dw\nlQesdgP2EK7RI7LTSz4kk7ny+ll+XQ2c8Qk4iNVZWZ4XdsJOlc/ky8HiQgrUGskr\ni2q2dohmoKdFAWaWPbS4NQdAqi770I64MW8+6k1xNgH+KYiE57yFSbycL9lF1iw2\n7bjqrI/FAgMBAAECggEAEzG2NDWFffmzjb/V2Qzxrt6FwNomFCHZs/Fgel4CLdk/\nv6z80LSiSVPmbzs6+boX61HgzCAXP8nHq8fb0EUDWz+l+zWVMIv2+Uv4OsawdWk7\ntFxPm4q17gN25IWb8C3JAI3ZCQfH4XiRli30lKAOCNvXMnioW7YRQTo5sSWZ4lHT\n8zm1TVp/zQDdbpWT/aCDpgd2hCWl8lqTngBvsAnpYPIqYkE2TbYbnp/WaHiK2wtO\nq3XKSul4LjRtkqeDo9uBbMa6fFueYORMolwLVBnhNWAycukQba97WmCf3wBNdlAI\nQTYZpk8nWbYTZe73q7DnNJ/3qjczMK1wY0dKEnxNDQKBgQDjYAxnWbE/2RqGxXyi\nFThM5FYMabwZdOcq3QoMaNRYXO9fk/7PaI2js5ZJp/ztgMDJ5+Mi1VgSNfEeX4RX\nJODUBzDktz+sjXP9xk0rwZQ4ND1FTnG3oqbBaMUu10BXSe4VDk8Y5Fb95T4S0eE9\nVAbQkVGZti9mmYu85iGhLvBgPwKBgQDRul4AShJ/kAZ5LVuYOtpx3q0do31Ag0Gb\nFaA47JuDYczV6fLw4KkBkG/sPnGjgVaZM3awpMg+UTeayFIDnn/TGkqjbeB8z7R/\nZpUIGLz2ChNTScpHKnxCz5u8Eemnhuo5oD3knG5TCh0ecfu7fZW2yNJ7S6Qfu4tV\nK0eMnZVO+wKBgFVR5VWiwnBC90E7OdlYPRgdVmyyAHNM+rGK4ApoC8ZcmTY0Qplx\nkjSrXumkr7QvbChXa1PW2oV62E+dZ/uLSxJE4IPyf2IwciX4E10n9oZgk9094k4W\nKpzIw7Uf8HTQuRYNmICurjX3n6NQPkTVEvmQjh4vzvmhBF6NvHDPPEPhAoGBAKnB\nRZDKY8qokvTGR9sh1+pPKKRSznDHTPTwPi2VJhLjuF507FUYIvPHKzB3IpgLekKq\nqykzV3lJV86K0gdn5WLDZyJ9LzUXEawFJh/Vli033oiNs5KCyu1xCUbi4NLemvtl\nvnMqQwonp4YbEHyjm+jFB8kQYpnkvVSEoXcpnc69AoGAdHPsg68PQgLtVrO1HV/v\nnkFLq9VFCL9xVHQxmcSHMna+wOxHQJ05zAr2WkW3PMhD78UdAvQ1TqCTLki4WW7C\n6u3DimMZxOtyhF0R5cPl9OwIIlkYpcyHms49v37SZ7NnPVwG1H8feCYXphYJJ5wW\ngPBNgni33x6jS9dW1S5DFjY=\n-----END PRIVATE KEY-----\n"
client_email = "streamlit@kognisi-dashboard.iam.gserviceaccount.com"
client_id = "101307106449434012143"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit%40kognisi-dashboard.iam.gserviceaccount.com"

[sheets]
type = "service_account"
project_id = "data-team-451307"
private_key_id = "bf257cc142748cd956d9b582eeabfe73bbe28193"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCe4zmKJpFk4r+c
CCDCiehyWUVCUisT1vLHIZuV/yOmQMlEfr/3YvtgbvFUtFUsgqVTLmkHcE0mkOHC
DOacgEt1HxY5tNJIr6r1z7X7namId4F/qRoR8BrCQto8yCv0AJBd8tazU0QCOmfB
c1W+2P6N1BkBFnw1pyVJ381AETmpt5MazAKdgfr4gGE9+cbo48aqz9w1MesewW35
qerSK2AkmjQblBOZXxWqJlPcRPv/QlAVec9QA4DkmKwAvXlRSc877xf8JdCJE2wn
KG+OTsaZ+NOS5Hnw5asn1g53AQIRTk2H48FzSLcByLWiO7ZtBPil8l3/P4uqRCXb
PayIuJmrAgMBAAECggEAQXPecLRJodMs1sScZjd0a6Ktvs/lkgMyuOh11PkpQOQg
ZViHkQwT/NpHDTtKeQ8KtvT/7EINbi0x6wPwfhj1vLZFLBl6pNnE5gUedRwyShbc
4G+TXz9Xbp4mk/Jr9NTEpAcU/gN3mSlhM5ZlBL0UQ+3TLRkLqviDimapAVL3O5vP
TPQxR/8dY8ACvqIWCAIlD10Vwb+K9y2COTw/NSv5051urynQ2DUtUcSm3fBvNCzs
vnw/RxhYmu84iiND9tNCTlTfEyuGt4G1YMbCwn6Xcc+cxi0uq/QVTEM1OI6BCq0J
PCNmqPu1bouE7bR5Fh6WaE77RQMzrvnu0hxj6uSgIQKBgQDM1AUPsLW7gSozPbPB
TSvrB6TqI5+A2R7B/8cRGMqMImj2g3n5st7QMkikWiCp2++ZSIBl016G2K2EMFAD
uBUwpyGQ0KQs45hea6XpHVuyly5FqEzgZd6cepczJRxjuA7vA4UKS+QZvrPSPh8D
FIqG7lMRR06p/a3iowoRQG6kCwKBgQDGlQfHEAL2U0RFtdkcV2HEWAhshUqz57ol
c8qoIwxDtbvO59k94/WnOiVDCyUXoXrc9poWkK3zLIZ7R3w1TW4NiJLbVvfETafg
urUQ1+L97qGVw9kBe5BtBxYKQUv5r4ztIBe97OXIp9iqgRdUrq5HfknJelzemaZL
X7tGcObE4QKBgFsrqFESk+GxHYqPVVqeMgU8ctBxKMceXY12fzIB+e4kRtorLXjS
gFDlgOX+4/kXV2/AEL7CNZoKCjoDkyoEnxH34n3mEJ2WdLTab4/yrGUy27rPreBY
F51JB9IRG7DbNXJ3+5jYrOA0vS/AzOb/FqX2oOzY84/AxcxSS+Hf7x9/AoGBAJIq
M5VTtbp1Q3VEClAQCUgpu9mUqo2M7LiQaAQl9+sGovwCLyac2b2C0NZuJ5kjJHnr
kTM2vrKUfU/UKBpbqbuQYPfNJYV52y1Qf+Gr5coekRTZGKs8tetqIdDeivt3OXV3
/8Gt0txEnvexGOkdwe2hiNIhnKXD1mD4T7HjfBhBAoGADGrpFhys6R5ki5Rf0MJo
LrqYCl8GCcPvp/QCKG6lj0eXYWS1wmhFNffysTWZLD5z3DuYrcpA2LCmGA8M0G6h
/etIChC6LaqXAz4Z4KQ/khDTNM4xHZUFmKGAg6drAx/GmTZUrAuGJrMeYHVBs6Zk
Dx1xXvgj3qERn/o80Itvf98=
-----END PRIVATE KEY-----"""
client_email = "data101@data-team-451307.iam.gserviceaccount.com"
client_id = "103064373485072818881"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/data101%40data-team-451307.iam.gserviceaccount.com"
universe_domain = "googleapis.com"